config:
  # Labels and annotations to look for when scraping.
  labels:
    - prometheus.io/scrape
    - newrelic.com/scrape
  annotations:
    - prometheus.io/scrape
    - newrelic.com/scrape

  # How often to pull metrics from discovered targets.
  interval: 30s

  jobs:
    # Scrape pods annotated or labeled with the specified annotations, as well as endpoints behind annotated services.
    # All endpoints behind the service will be scraped individually.
    podsEndpoints:
      enabled: true
    # Scrape externalName services, which may point to exporters outside the Kubernetes cluster.
    # Keep in mind that for this job, the scraper needs to hit the load-balanced server IP directly, which can lead to
    # unexpected results if the service has multiple endpoints.
    external:
      enabled: false

  # Prometheus scrape configs to add to the prometheus receiver.
  # See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
  extraScrapeConfigs: []

  # Enable the OTEL batch processor.
  batchProcessor:
    enabled: true

  # If enabled, this flag will add two pre-configured processors which apply some transformations to labels and
  # attributes to match the conventions used by New Relic.
  # It MUST be enabled if you are sending data to New Relic.
  nrConventionsProcessors:
    enabled: false

  # Extra configs to use as processors for the otel collector.
  # By adding more processors here, metrics can be filtered or transformed with a high degree of flexibility, e.g.:
  # - Filter: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor
  # - Transform: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor
  # More: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor
  # Processors defined here will be automatically added at the end of the metrics pipeline.
  extraProcessors: {}
    #filter/kube:
    #  metrics:
    #    exclude:
    #      match_type: regexp
    #      metric_names:
    #        - kube_.*

  # Configure the logging exporter, which can log to stderr all the metrics received by the collector.
  # See: https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter
  loggingExporter:
    enabled: false
    loglevel: info

  # Configure the OTLP exporter, which would typically hit an in-cluster gateway collector.
  # Env var NR_LICENSE_KEY is available containing the New Relic license key, if it has been provided.
  # See: https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter
  otlpExporter:
    enabled: false
    endpoint: otlp.nr-data.net:4317
    headers:
      api-key: "${NR_LICENSE_KEY}"  # Added to the deployment's env by the chart automatically

  # Extra configs to use as exporters for the otel collector.
  # See: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter
  extraExporters: {}

service:
  # prometheusDebug exposes a port where you can query this collector for all the metrics it has gathered in the
  # OpenMetrics format. It is useful for troubleshooting and seeing what the collector is scraping.
  prometheusDebug:
    enabled: false
    type: ClusterIP
    port: 9000
    annotations: {}

# ---

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Whether to automatically create RBAC rules.
# This chart requires (and by default will create on its own) RBAC granting read-only (get, list, watch) permission to:
#  - nodes
#  - pods
#  - services
#  - endpoints
rbac:
  create: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
