apiVersion: v2
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet, supporting both Linux and Windows nodes and containers
name: newrelic-logging
<<<<<<< HEAD
version: 1.11.3
appVersion: 1.14.0
=======
version: 1.11.0
appVersion: 1.10.0
>>>>>>> 8650c588 ([newrelic-loggin] Bump chart minor version)
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: jsubirat
    email: logging-team@newrelic.com
  - name: danybmx
  - name: sdaubin
keywords:
  - logging
  - newrelic
dependencies:
  - name: common-library
    version: 1.0.5
    repository: "https://helm-charts.newrelic.com"
