{{- if not (include "newrelic.licenseCustomSecretName" .) | and (include "newrelic.licenseKey" .) }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-license
type: Opaque
data:
  licenseKey: {{ include "newrelic.licenseKey" . | b64enc }}
{{- end }}
