{{ if .Values.kubelet.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-kubelet
data:
  nri-kubernetes-config.yml: |
{{ toYaml (merge (include "newrelic.kubelet.scraperConfig" . | fromYaml) .Values.common.scraperConfig) | indent 6 }}
{{ end }}
