{{ if .Values.controlPlane.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-control-plane
data:
  nri-kubernetes-config.yml: |
# The component's scraperConfig and the common scrapper values are merged
# if a specific common value is not set on the component, the one in the common will be the one used (Example: interval)
{{ toYaml (merge (include "newrelic.controlPlane.scraperConfig" . | fromYaml) .Values.common.scraperConfig) | indent 6 }}
{{ end }}
