{{- $namespaces := include "newrelic.roleBindingNamespaces" . | fromYaml -}}
{{if $namespaces.roleBindingNamespaces}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "newrelic.serviceAccountName" . }}-control-plane
  labels: {{ include "newrelic.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}