{{ if .Values.ksm.enabled }}
{{- $deprecatedKubeStateMetrics := include "newrelic.deprecatedKubeStateMetrics" . | fromYaml -}}
{{- $scraperConfig := include "newrelic.ksm.scraperConfig" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels: {{ include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-ksm
data:
  nri-kubernetes-config.yml: |
{{ toYaml (merge ($deprecatedKubeStateMetrics) ($scraperConfig) .Values.common.scraperConfig) | indent 6 }}
{{ end }}
